# Generated by Django 3.0.8 on 2020-07-28 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_last_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 18, 48, 47, 174951, tzinfo=utc)),
        ),
    ]
