# Generated by Django 3.0.8 on 2020-07-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='areFriends',
            field=models.BooleanField(default=False),
        ),
    ]
