# Generated by Django 3.0.8 on 2020-08-04 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contact_arefriends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_one_friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='second_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_two_friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
